BOKHYLLAN/website/views.py
"""
Vi har importerat olika paket från flask som redan finns redo för att kunna
bygga de olika funktionena i programmet
Blueprint hjälper oss att dela upp projektet och sortera i olika filer.
Render_template används för att flask ska kunna använda sig av html, 
Request hjälper oss för att kunna använda POST-method och GET-method,
Flash pop up meddelanderna. 
Redirect och url_for hänvisar oss till funktion eller path.
Current_app använder vi för att konfigurera själva appen.
werkzeug.utils hjälper till att säkra alla filer och kod.
secure_filename files namn.
uuid funktionene skapar ett unik namn för filen, blandar det och krypterar
datum samt tid för överlappande av filen.
os är en del av standarbiblioteket, låter användaren interagera med det inbyggda operativsystemet phyton körs på
"""
from flask import Blueprint, render_template, request, flash, redirect, url_for, current_app, abort, session
from flask_login import login_required, current_user
from .models import User, Book, Rooms, ReadingChallenge
from . import db
from werkzeug.utils import secure_filename
from flask_socketio import SocketIO, send, join_room, leave_room
from string import ascii_uppercase
from flask import jsonify
import uuid as uuid
import os
import random
import json


'''Variabel för blueprint. Detta organiserar appen/programmet'''
views = Blueprint('views', __name__)
rooms = {} 
socketio = SocketIO()

'''Hanterar redigering av en bok baserat på bokens ID.'''
@views.route('/edit-book/<int:book_id>', methods=['GET', 'POST'])
@login_required
def edit_book(book_id):
    book = Book.query.get(book_id)
    if request.method == 'POST':        
        new_title = request.form.get('new_title')
        new_author = request.form.get('new_author')
        new_isbn = request.form.get('new_isbn')
        new_review = request.form.get('new_review')
        book.title = new_title
        book.author = new_author
        book.isbn = new_isbn
        book.review = new_review
        db.session.commit()
        flash('Boken har uppdaterats!', category='success')
        return redirect(url_for('views.home'))
    
    return render_template("edit_book.html",user = current_user, book = book)


def generate_room(length):
    while True:
        room_code = ''.join(random.choice(ascii_uppercase) for _ in range(length))
        existing_room = Rooms.query.filter_by(room_code=room_code).first()

        if not existing_room:
            existing_room = Rooms()
            existing_room.room_code = room_code
            db.session.commit()
            break

    return room_code


@views.route("/chat/<int:owner_id>", methods= ['POST'])
@login_required
def chat(owner_id):
        session.clear()
        if request.method == "POST": 
            book_owner_id = owner_id
            user_1 = User.query.get(current_user.id)
            user_1_name = user_1.first_name
            user_1_id = user_1.id
            user_2 = User.query.get(book_owner_id)
            user_2_name = user_2.first_name
            user_2_id = user_2.id
            email = user_2.email
            
            existing_room = Rooms.query.filter_by(user_1_id=user_1_id, user_2_id=user_2_id).first()

            if existing_room:
                return render_template("chat_room.html", 
                               user_1 = user_1_name, 
                               user_2 = user_2_name,
                               email = email, 
                               user = current_user, 
                               room_code = existing_room.room_code)
            else:
                new_room_code = generate_room(6)
                new_chat = Rooms(user_1_id=user_1_id, user_2_id=user_2_id, room_code=new_room_code)
                db.session.add(new_chat)
                db.session.commit()

            room_data = {"members": 0, "messages": []}
            room_json = json.dumps(room_data)

            session["room"] = room_json
            session["name"] = user_1_name
        
        return render_template("chat_room.html", 
                               user_1 = user_1_name, 
                               user_2 = user_2_name,
                               email = email,
                               user = current_user, 
                               room_code = new_room_code)


@socketio.on("message")
def message(data):
    room = session.get("room")
    if room not in rooms:
        return 
    
    content = {
        "name": session.get("name"),
        "message": data["data"]
    }
    send(content, to=room)
    rooms[room]["messages"].append(content)
    print(f"{session.get('name')} said: {data['data']}")


@socketio.on("connect")
def connect(auth):
    room = session.get("room")
    name = session.get("name")
    if not room or not name:
        return
    if room not in rooms:
        leave_room(room)
        return
    
    join_room(room)
    send({"name": name, "message": "has entered the room"}, to=room)
    print(f"{name} joined room {room}")


@socketio.on("disconnect")
def disconnect():
    room = session.get("room")
    name = session.get("name")
    leave_room(room)

    
    send({"name": name, "message": "has left the room"}, to=room)
    print(f"{name} has left the room {room}")

""" Renderar en boksida för en specifik bok baserat på bokens ID. """
@views.route('/book-file/<int:book_id>', methods=['GET'])
@login_required
def book_file(book_id):
    book = Book.query.get(book_id)
    id_owner = book.user_id
    user = User.query.filter_by(id=current_user.id).first()
    owner = User.query.filter_by(id=id_owner).first()
    
    return render_template('book_page.html', book=book, user = user, owner= owner)


"""Denna funktion (sökfunktion) söker efter boken i databasen. Denna funktion valdes
för att den letar fram liknande resultat till sökningen som användaren gör. """
@views.route('/search', methods=["POST"])
def search():
    form = request.form.get('searched')
    books = Book.query.filter_by().all()
    if form:
            books_result = Book.query.filter(
            (Book.title.ilike(f'%{form}%')) |
            (Book.author.ilike(f'%{form}%')) |
            (Book.isbn.ilike(f'%{form}%'))
        ).all()
    else:
        books_result = []
    
    print(books_result)
    return render_template("search.html", user=current_user, searched = form, books =books , result= books_result)


'''Funktion för route till homepage'''
@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    books = Book.query.filter_by(user_id=current_user.id).all()
    return render_template("home.html", user=current_user, books=books)


'''Funktion för visning av biblioteket av samtliga uppladdade böcker'''
@views.route('/all-books')
@login_required
def show_all_books():
    books = Book.query.all()
    return render_template('all_books.html', user=current_user, books=books )


'''Funktion för att användaren ska kunna lägga till en bok för utbyte.
Boken läggs in i databasen samt visas på home.html'''
@views.route('/add-book', methods=['GET', 'POST'])
@login_required
def add_book():
    books = Book.query.filter_by(user_id=current_user.id).all()

    if request.method == 'POST':
        user = User.query.filter_by(id=current_user.id).first()
        cover = request.files['cover']
        cover_name = secure_filename(cover.filename)
        cover_file_name = str(uuid.uuid1()) + "_" + cover_name        
        title = request.form.get('title')
        author = request.form.get('author')
        isbn = request.form.get('isbn')
        review = request.form.get('review')
        if 'cover' not in request.files:
            flash('Bilden har inte sparat!', category='error')
            return redirect(url_for('views.add_book'))
        if cover_name == '':
            flash('Ingen fil har valts')
            return redirect(url_for('views.add_book'))
        if allowed_file(cover.filename) == False:
            flash('filformat inte tillåtet!')
            return redirect(url_for('views.add_book'))
        else:
            cover and allowed_file(cover.filename)
            cover.save(os.path.join(current_app.config['UPLOAD_FOLDER'], cover_file_name))
            new_book = Book(title=title,author=author, isbn=isbn, review=review, user_id=current_user.id, cover_pic= cover_file_name )
            user.score = user.score + 1
            db.session.add(new_book)
            db.session.commit()
            flash('Boken har laddats upp!', category='success')
            return redirect(url_for('views.home'))
    
    return render_template('add_book.html', user=current_user, books=books )
    

'''Funktion för att ta bort en uppladdad bok'''
@views.route('/remove-book/<int:book_id>', methods=['POST'])
@login_required
def remove_book(book_id):
    book = Book.query.get(book_id)
    user = User.query.filter_by(id=current_user.id).first()

    if book.user_id == current_user.id:
        db.session.delete(book)
        user.score = user.score - 1
        db.session.commit()
        flash('Boken har tagits bort!', category='success')
    else:
        flash('Du kan bara ta bort dina egna böcker!', category='error')
    return redirect(url_for('views.add_book'))


'''Funktioner för att ladda upp profilbild'''
ALLOWED_EXTENSIONS = { 'jpg', 'jpeg','gif'} #denna är de filerna som är godkänns för att ladda upp.

#jämföra filens namn med den typ av fil som godkänns av programmet, dvs jpg och jpeg. 
def allowed_file(pic_name):
    return '.' in pic_name and \
           pic_name.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


#denna funktionen är till för att ta bort profilbilden från användaren där den automatiskt ta bort den gamla. 
def delete_old_pic():
    user = User.query.filter_by(id=current_user.id).first()
    old_profile_pic = str(user.profile_pic)
    path = str('./BOKHYLLAN/website/static/images/'+ old_profile_pic)
    if user.profile_pic  == old_profile_pic and user.profile_pic != "":
        os.remove(path)


#vi kommer att kommentera varje rad:

BOKHYLLAN/website/templates/add_book.html
{% extends "base.html" %}
{% block title %}Ladda up bok{% endblock %}
{% block content %}
<!--Formulär för att ladda upp ny bok och att ta bort en bok ligger på denna sida.-->

  <div id="add-book-div">
    <h1>Ladda upp en bok att byta ut</h1>

      <form action="/add-book" id="add-book-form" method="POST" enctype="multipart/form-data">
        <div class="form-group">
          <label for="title">Titel</label>
          <input type="text" class="form-control" name="title" id="title" required>
        </div>

        <div class="form-group">
          <label for="author">Författare</label>
          <input type="text" class="form-control" name="author" id="author" required>
        </div>

        <div class="form-group">
          <label for="isbn">ISBN</label>
          <input type="text" class="form-control" name="isbn" id="isbn">
        </div>

        <div class="form-group">
          <label for="review">Beskrivning</label>
          <p id="add-book-text">Exempelvis bokens handling eller bokens skick (nyskick, välanvänd etc)</p>
          <textarea class="form-control" name="review" id="review" rows="8" required></textarea> 
        </div>

        <label>Klicka på fältet och välj bilden du vill ladda upp</label>
        <div class="custom-file">
            <input type="file" class="custom-file-input" name="cover">
            <label class="custom-file-label" for="cover" placeholder=""></label>
        </div>
        <button type="submit" class="btn btn-primary">Ladda upp bok</button>
      </form>

  </div>
    
{% endblock %}

BOKHYLLAN/website/templates/all_books.html
{% extends "base.html" %}

{% block title %}Bokhyllan{% endblock %}

{% block content %}
<div id="all-books-div">
    <div id="search-div">
        <form method="POST" action="/search" class="form-inline my-2 my-lg-0">
            <input name="searched" class="form-control mr-sm-2" type="search" placeholder="Titel, författare..."
                aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Sök</button>
        </form>
    </div>

    {% for book in books %}
    <div id="book-list-div">
        <a href="{{ url_for('views.book_file', book_id=book.id) }}">
            <div id="book-list-img-div">
                {% if book.cover_pic %}
                <img src="{{ url_for('static', filename='images/' + book.cover_pic) }}" alt="#" class="rounded-circle"
                    align="left">
                {% else %}
                <img src="{{ url_for('static', filename='images/emty_profile.jpg') }}" alt="#" class="rounded-circle"
                    align="left">
                {% endif %}

                <ul id="book-list">
                    <li>
                        Titel: {{ book.title }}
                    </li>
                    <li>
                        Författare: {{ book.author }}
                    </li>
                    <li>
                        ISBN: {{ book.isbn }}
                    </li>
                    <li>
                        Beskrivning:
                        {% if book.review|length > 100 %}
                        {{ book.review[:70] }}
                        {% else %}
                        {{ book.review }}
                        {% endif %}
                    </li>
        </a>
        <li>
            {% if current_user.is_authenticated %}
            {% if book in current_user.favorite_books %}
            <button class="favorite-button" data-book-id="{{ book.id }}">
                <i class="fas fa-star"></i> Unfavorite
            </button>
            {% else %}
            <button class="favorite-button" data-book-id="{{ book.id }}">
                <i class="far fa-star"></i> Favorite
            </button>
            {% endif %}
            {% endif %}
        </li>
        </ul>
    </div>

</div>
{% endfor %}
</div>

<script>
    document.getElementById('all-books-div').addEventListener('click', function(event) {
        if (event.target.matches('.favorite-button')) {
            const bookId = event.target.getAttribute('data-book-id');
            toggleFavorite(bookId);
        }
    });

    function toggleFavorite(bookId) {
        fetch('/toggle_favorite/' + bookId, { method: 'POST' })
            .then(response => response.json())
            .then(data => {
                if (data.status === 'success') {
                    const favoriteButton = document.querySelector(`[data-book-id="${bookId}"]`);
                    if (favoriteButton.innerHTML.includes('Unfavorite')) {
                        favoriteButton.innerHTML = '<i class="far fa-star"></i> Favorite';
                    } else {
                        favoriteButton.innerHTML = '<i class="fas fa-star"></i> Unfavorite';
                    }
                }
            })
            .catch(error => {
                console.error('Error:', error);
            });
    }
</script>

{% endblock %}

BOKHYLLAN/website/templates/base.html
<!--detta är basen till alla html som behöver. navigeringsfället ändras om användaren är inloggad-->
<!--under utvecklingen använde jag Bootstrap-webbplatsen version 4.3 att fokusera på strukturen för phytonkoden. BS kan ersättas med
en mer anständig version eller med var egen html och css kod-->
<!--om du vill lägga till ngn csskod finns sökvägen edan och filen finns i mappen .static/CSS/style.css-->
<!DOCTYPE html>
<html lang="en">
<!-- Ska det verkligen vara engelska, inte svenska?-->

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title> {% block title%} {% endblock %}</title>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/style.css')}}">
</head>

<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          {% if user.is_authenticated %}
          <a class="navbar-brand" id="home" href="/">
            <img src="{{url_for('static', filename='images/logo-transparent.png')}}" width="30" height="30" alt="logo">
          </a>
          <!--
          <a class="nav-link" id="home" href="/">Bokhyllan<span class="sr-only">(current)</span></a>
          -->
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Böcker
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" id="all-books-nav" href="/all-books">Alla böcker</a>
            <a class="dropdown-item" id="random-book-nav" href="/random-book">Slumpa fram en bok</a>
            <a class="dropdown-item" id="user-books-nav" href="/user-books">Min bokhylla</a>
            <a class="dropdown-item" id="add-book-nav" href="/my-challenges">Mina läsutmaningar</a>
            <a class="dropdown-item" id="add-book-nav" href="/add-book">Ladda upp en bok</a>
          </div>
        <li class="nav-item">
          <a class="nav-link" href="/policy">Användarvillkor</a>
          {% endif %}
        </li>
        {% if user.is_authenticated %}
        <!-- Nav drop down som kopplas till javascrip som gör det möjligt att ändra färgapalett på sidan. -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="valjdinfarg" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Välj din färg!
          </a>
          <div class="dropdown-menu" aria-labelledby="valjdinfarg">
            <a class="dropdown-item no-bullet" href="#" onclick="setTheme('default')">Default</a>
            <a class="dropdown-item no-bullet" href="#" onclick="setTheme('dark')">Inverterad</a>
          </div>
          {% endif %}

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Profil
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if not user.is_authenticated %}
            <a class="dropdown-item" id="login" href="/login">Logga in</a>
            <a class="dropdown-item" id="signUp" href="/sign-up">Registrera</a>
            {% endif %}
            {% if user.is_authenticated %}
            <a class="dropdown-item" id="redigera_profil" href="/edit-profile">Redigera profil</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" id="logout" href="/logout">Logga ut</a>
            {% endif %}
          </div>
        </li>
        </li>
      </ul>
    </div>
  </nav>

<!-- Flashmeddelande under navbar -->
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      {% if category == 'error' %}
        <div class="alert alert-danger alert-dismissible fade show fade-out" role="alert" id="flash-message">
          {{ message }}
        </div>
      {% else %}
        <div class="alert alert-success alert-dismissible fade show fade-out" role="alert" id="flash-message">
          {{ message }}
        </div>
      {% endif %}
    {% endfor %}
  {% endif %}
{% endwith %}


  <script>
    setTimeout(function() {
      var flashMessage = document.getElementById('flash-message');
      if (flashMessage) {
        flashMessage.style.display = 'none';
      }
    }, 5000);
  </script>



  <!-- Container för respektive sidas huvudinnehåll -->
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


  <!-- Går det att ändra indenteringen här eller fuckar allt då? /J-->
  {% block javascript %}
  <script type="text/javascript">
    function deleteBio(bioId) {
      fetch("/delete-bio", {
        method: "POST",
        body: JSON.stringify({ bioId: bioId }),
      }).then((_res) => {
        window.location.href = "/";
      });
    }
  </script>
  {% endblock %}

  <script>
    // Function to activate the selected theme
    function setTheme(theme) {
      const body = document.querySelector('body');
      const navbar = document.querySelector('.navbar');
      const navbarTogglerIcon = document.querySelector('.navbar-toggler-icon');
      const navbarToggler = document.querySelector('.navbar-toggler');
  
      switch (theme) {
        case 'default':
          body.classList.remove('dark'); // Remove the 'dark' class from body
          navbar.classList.remove('navbar-dark'); // Remove the 'navbar-dark' class from navbar
          navbarTogglerIcon.classList.remove('dark-icon'); // Remove the 'dark-icon' class from the toggler icon
          navbarToggler.classList.remove('dark-button'); // Remove the 'dark-button' class from the toggler button
          break;
        case 'dark':
          body.classList.add('dark'); // Add the 'dark' class to body
          navbar.classList.add('navbar-dark'); // Add the 'navbar-dark' class to navbar
          navbarTogglerIcon.classList.add('dark-icon'); // Add the 'dark-icon' class to the toggler icon
          navbarToggler.classList.add('dark-button'); // Add the 'dark-button' class to the toggler button
          break;  
      }
  
      // Store the selected theme
      localStorage.setItem('selectedTheme', theme);
    }
  
    // Check local storage to maintain the selected theme consistency
    const selectedTheme = localStorage.getItem('selectedTheme');
    if (selectedTheme) {
      setTheme(selectedTheme);
    }
  </script>

</body>

</html>

BOKHYLLAN/website/templates/create_challenge.html
{% extends "base.html" %}

{% block content %}
  <h1>Skapa en ny läsutmaning</h1>
  <form method="POST">
      <input type="text" name="goal" placeholder="Döp ditt mål" required>
      <input type="number" name="target_number" placeholder="Antal böcker" required>
      <button type="submit">Skapa Utmaning</button>
      <p>Här kan du skapa en läsutmaning, du döper ditt mål och fyller i hur många böcker du hoppas läsa.</p>
  </form>
{% endblock %}

BOKHYLLAN/website/templates/edit_book.html
{% extends "base.html" %}
{% block title %}Redigera bok{% endblock %}
{% block content %}

<div id="edit-book-div">

    <h2>Redigera boken {{book.title}} - {{book.author}}</h2>
    <form id="edit-book-form" method="POST" action="{{ url_for('views.edit_book', book_id=book.id) }}">
        <div class="form-group">
            <label for="new_title">Ny titel</label>
            <input type="text" class="form-control" id="new_title" name="new_title" value="{{ book.title }}">
        </div>
        <div class="form-group">
            <label for="new_author">Ny författare</label>
            <input type="text" class="form-control" id="new_author" name="new_author" value="{{ book.author }}">
        </div>
        <div class="form-group">
            <label for="new_isbn">Nytt ISBN</label>
            <input type="text" class="form-control" id="new_isbn" name="new_isbn" value="{{ book.isbn }}">
        </div>
        <div class="form-group">
            <label for="new_review">Ny beskrivning</label>
            <textarea class="form-control" id="new_review" name="new_review">{{ book.review }}</textarea>
        </div>
        <div class="form-group form-check">
            <input type="checkbox" class="form-check-input" id="Check1" required>
            <label class="form-check-label" for="Check1">Bekräfta ändringarna</label>
        </div>
        <button type="submit" class="btn btn-primary">Uppdatera</button>
    </form>

    <div id="delete-book-div">
        <h3>Vill du ta bort boken?</h3>
        <form method="POST" action="{{ url_for('views.remove_book', book_id=book.id) }}">
            <button type="submit" class="btn btn-primary">Ta bort</button>
        </form>
    </div>

    
</div>

{% endblock %}

BOKHYLLAN/website/templates/home.html
{% extends "base.html" %}
{% block title %}Home Page{% endblock %}
{% block content %}

<div id="home-div">

  <div id="user-header">
    <h1>Hej, {{ user.first_name }}!</h1>
  </div>

  <div id="user-info-div">

    <div id="user-pic">
      {% if user.profile_pic %}
      <a href="/add-pic">
        <div class="profile-pic-wrapper">
          <img src="{{ url_for('static', filename='images/' + user.profile_pic) }}" alt="profile_img" class="rounded-circle">
          <div class="profile-pic-overlay">
            <span class="overlay-text">Ändra profilbild</span>
          </div>
        </div>
      </a>
      {% else %}
      <a href="/add-pic">
        <div class="profile-pic-wrapper">
          <img src="{{ url_for('static', filename='images/emty_profile.jpg') }}" alt="profile_img" class="rounded-circle">
          <div class="profile-pic-overlay">
            <span class="overlay-text">Ändra profilbild</span>
          </div>
        </div>
      </a>
      {% endif %}
    </div>


    <div id="user-bio">
      <h2>Biografi</h2>
      {% if user.bio %}
      <p>{{ user.bio }}</p>
      <a class="button" id="addBio" href="/add-bio"><button type="button" class="btn btn-primary">Ändra bio</button></a>
      {% else %}
      <a class="button" id="addBio" href="/add-bio"><button type="button" class="btn btn-primary">Lägg till bio</button></a>
      {% endif %}
    </div>

    <div id="user-points">
      {% if user.score %}
      <h3>Poäng: {{ user.score }}</h3>
      {% else %}
      <h3>Poäng: 0</h3>
      {% endif %}
    </div>

  </div>

  <div id="user-books">
    <h1>Dina böcker</h1>
    {% for book in books %}
    <div class="book">
      <h3>
        <a href="{{ url_for('views.book_file', book_id=book.id) }}">
          {{ book.title }}
        </a>
      </h3>
    </div>
    {% endfor %}
  </div>

  <div id="user-challenges">
    <h1>Läsutmaningar</h1>
    <a href="{{ url_for('views.my_challenges') }}" class="btn btn-secondary">Visa mina läsutmaningar</a>
  </div>
  

  <div id="user-favorites">
    <h1>Favoritböcker</h1>
    {% for favorite in user.favorite_books %}
    <div class="book">
      <h3>
        <a href="{{ url_for('views.book_file', book_id=favorite.id) }}">
          {{ favorite.title }}
        </a>
      </h3>
    </div>
    {% endfor %}
  </div>

</div>

{% endblock %}

BOKHYLLAN/website/templates/user_books.html
{% extends "base.html" %}
{% block title %}Mina bokhylla{% endblock %}
{% block content %}
<!-- Ska innehålla en lista över användarens egna böcker samt möjligtheten att redigera och radera dem-->

    <div id="user-books-div">
        <h1>Min bokhylla</h1>

        {% for book in books %}
        <div id="book-list-div">
            <a href="{{ url_for('views.book_file', book_id=book.id) }}">

                <div id="book-list-img-div">
                {% if book.cover_pic %}
                    <img src="{{url_for('static', filename='images/' + book.cover_pic)}}" alt="#" class="rounded-circle" align="left">
                {%else%}
                    <img src="{{url_for('static', filename='images/emty_profile.jpg')}}" alt="#" class="rounded-circle" align="left">
                {%endif%}

                    <ul id="book-list">
                        <li>
                            Titel:  {{book.title}}
                        </li>
                        <li>
                            Författare:  {{book.author}}
                        </li>
                        <li>
                            ISBN: {{book.isbn}}
                        </li>
                        <li>
                            Beskrivning: 
                            {% if book.review|length > 100 %}
                                {{ book.review[:100] }}
                            {% else %}
                                {{ book.review }}
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </a>


                <form method="GET" action="{{ url_for('views.edit_book', book_id=book.id) }}">
                    <button type="submit" class="btn btn-primary">Redigera</button>
                </form>


        </div>
        {%endfor%}

    </div>
{% endblock %}